# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-03 21:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('apellido_paterno', models.CharField(max_length=100)),
                ('apellido_materno', models.CharField(max_length=100)),
                ('razon_social', models.CharField(max_length=100)),
                ('rfc', models.CharField(max_length=15, verbose_name='RFC')),
                ('telefono', models.CharField(max_length=12)),
                ('telefono_celular', models.CharField(max_length=12)),
                ('fecha_nacimiento', models.DateField()),
            ],
        ),
    ]
